# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

env:
  ENV: development

dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

tasks:
  build:
    desc: Build backend
    dir: backend
    cmds:
      - go build -o ../bin/server ./cmd/server

  run:
    desc: Run backend
    dir: backend
    cmds:
      - go run ./cmd/server

  install:
    desc: Install backend dependencies
    dir: backend
    cmds:
      - go mod tidy

  test-unit:
    desc: Run backend unit tests
    dir: backend
    cmds:
      - go test -v

  # DB
  schema-new:
    desc: Create a new sql sequence in migrations
    dir: backend
    cmds:
      - migrate create -ext sql -dir migrations -seq {{.CLI_ARGS}}

  migrate-up:
    desc: Run migrations on Supabase
    dir: backend
    cmds:
      - migrate -path migrations -database "$DATABASE_URL" up

  migrate-down:
    desc: Run migrations on Supabase
    dir: backend
    cmds:
      - migrate -path migrations -database "$DATABASE_URL" down
