//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type CourseSessionType string

const (
	CourseSessionType_Lab      CourseSessionType = "lab"
	CourseSessionType_Tutorial CourseSessionType = "tutorial"
	CourseSessionType_Lecture  CourseSessionType = "lecture"
)

var CourseSessionTypeAllValues = []CourseSessionType{
	CourseSessionType_Lab,
	CourseSessionType_Tutorial,
	CourseSessionType_Lecture,
}

func (e *CourseSessionType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "lab":
		*e = CourseSessionType_Lab
	case "tutorial":
		*e = CourseSessionType_Tutorial
	case "lecture":
		*e = CourseSessionType_Lecture
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for CourseSessionType enum")
	}

	return nil
}

func (e CourseSessionType) String() string {
	return string(e)
}
