//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

// Defines scheduling requirements for each course (e.g., "Calculus I needs 2 lectures and 1 tutorial per week")
type CourseSessions struct {
	ID               uuid.UUID `sql:"primary_key"`
	CourseID         uuid.UUID
	RequiredRoom     string            // Room type needed (e.g., lecture_room, computer_lab)
	Type             CourseSessionType // Session type: lecture, lab, or tutorial
	Duration         *int32            // Session length in minutes
	NumberOfSessions *int32            // How many times per week this session occurs
}
