//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Rooms struct {
	ID        uuid.UUID `sql:"primary_key"`
	Name      string
	Type      string
	Building  uuid.UUID
	Capacity  int32
	CreatedAt *time.Time
}
