//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

// Stores the output of the scheduling algorithm
type Schedules struct {
	ID        uuid.UUID `sql:"primary_key"`
	Name      *string   // Schedule identifier (e.g., Fall 2025 Schedule)
	CreatedAt *time.Time
	Sessions  string // JSONB array: [{course_id, room_id, day (0-6), start_time (mins), end_time (mins)}, ...]
}
