//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Building = newBuildingTable("scheduler", "building", "")

type buildingTable struct {
	postgres.Table

	// Columns
	ID   postgres.ColumnString
	Name postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type BuildingTable struct {
	buildingTable

	EXCLUDED buildingTable
}

// AS creates new BuildingTable with assigned alias
func (a BuildingTable) AS(alias string) *BuildingTable {
	return newBuildingTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BuildingTable with assigned schema name
func (a BuildingTable) FromSchema(schemaName string) *BuildingTable {
	return newBuildingTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BuildingTable with assigned table prefix
func (a BuildingTable) WithPrefix(prefix string) *BuildingTable {
	return newBuildingTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BuildingTable with assigned table suffix
func (a BuildingTable) WithSuffix(suffix string) *BuildingTable {
	return newBuildingTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBuildingTable(schemaName, tableName, alias string) *BuildingTable {
	return &BuildingTable{
		buildingTable: newBuildingTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newBuildingTableImpl("", "excluded", ""),
	}
}

func newBuildingTableImpl(schemaName, tableName, alias string) buildingTable {
	var (
		IDColumn       = postgres.StringColumn("id")
		NameColumn     = postgres.StringColumn("name")
		allColumns     = postgres.ColumnList{IDColumn, NameColumn}
		mutableColumns = postgres.ColumnList{NameColumn}
		defaultColumns = postgres.ColumnList{}
	)

	return buildingTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:   IDColumn,
		Name: NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
