//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Buildings = newBuildingsTable("scheduler", "buildings", "")

type buildingsTable struct {
	postgres.Table

	// Columns
	ID   postgres.ColumnString
	Name postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type BuildingsTable struct {
	buildingsTable

	EXCLUDED buildingsTable
}

// AS creates new BuildingsTable with assigned alias
func (a BuildingsTable) AS(alias string) *BuildingsTable {
	return newBuildingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BuildingsTable with assigned schema name
func (a BuildingsTable) FromSchema(schemaName string) *BuildingsTable {
	return newBuildingsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BuildingsTable with assigned table prefix
func (a BuildingsTable) WithPrefix(prefix string) *BuildingsTable {
	return newBuildingsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BuildingsTable with assigned table suffix
func (a BuildingsTable) WithSuffix(suffix string) *BuildingsTable {
	return newBuildingsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBuildingsTable(schemaName, tableName, alias string) *BuildingsTable {
	return &BuildingsTable{
		buildingsTable: newBuildingsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newBuildingsTableImpl("", "excluded", ""),
	}
}

func newBuildingsTableImpl(schemaName, tableName, alias string) buildingsTable {
	var (
		IDColumn       = postgres.StringColumn("id")
		NameColumn     = postgres.StringColumn("name")
		allColumns     = postgres.ColumnList{IDColumn, NameColumn}
		mutableColumns = postgres.ColumnList{NameColumn}
		defaultColumns = postgres.ColumnList{}
	)

	return buildingsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:   IDColumn,
		Name: NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
