//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CourseSessions = newCourseSessionsTable("scheduler", "course_sessions", "")

// Defines scheduling requirements for each course (e.g., "Calculus I needs 2 lectures and 1 tutorial per week")
type courseSessionsTable struct {
	postgres.Table

	// Columns
	ID               postgres.ColumnString
	CourseID         postgres.ColumnString
	RequiredRoom     postgres.ColumnString  // Room type needed (e.g., lecture_room, computer_lab)
	Type             postgres.ColumnString  // Session type: lecture, lab, or tutorial
	Duration         postgres.ColumnInteger // Session length in minutes
	NumberOfSessions postgres.ColumnInteger // How many times per week this session occurs

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CourseSessionsTable struct {
	courseSessionsTable

	EXCLUDED courseSessionsTable
}

// AS creates new CourseSessionsTable with assigned alias
func (a CourseSessionsTable) AS(alias string) *CourseSessionsTable {
	return newCourseSessionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CourseSessionsTable with assigned schema name
func (a CourseSessionsTable) FromSchema(schemaName string) *CourseSessionsTable {
	return newCourseSessionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CourseSessionsTable with assigned table prefix
func (a CourseSessionsTable) WithPrefix(prefix string) *CourseSessionsTable {
	return newCourseSessionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CourseSessionsTable with assigned table suffix
func (a CourseSessionsTable) WithSuffix(suffix string) *CourseSessionsTable {
	return newCourseSessionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCourseSessionsTable(schemaName, tableName, alias string) *CourseSessionsTable {
	return &CourseSessionsTable{
		courseSessionsTable: newCourseSessionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newCourseSessionsTableImpl("", "excluded", ""),
	}
}

func newCourseSessionsTableImpl(schemaName, tableName, alias string) courseSessionsTable {
	var (
		IDColumn               = postgres.StringColumn("id")
		CourseIDColumn         = postgres.StringColumn("course_id")
		RequiredRoomColumn     = postgres.StringColumn("required_room")
		TypeColumn             = postgres.StringColumn("type")
		DurationColumn         = postgres.IntegerColumn("duration")
		NumberOfSessionsColumn = postgres.IntegerColumn("number_of_sessions")
		allColumns             = postgres.ColumnList{IDColumn, CourseIDColumn, RequiredRoomColumn, TypeColumn, DurationColumn, NumberOfSessionsColumn}
		mutableColumns         = postgres.ColumnList{CourseIDColumn, RequiredRoomColumn, TypeColumn, DurationColumn, NumberOfSessionsColumn}
		defaultColumns         = postgres.ColumnList{}
	)

	return courseSessionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:               IDColumn,
		CourseID:         CourseIDColumn,
		RequiredRoom:     RequiredRoomColumn,
		Type:             TypeColumn,
		Duration:         DurationColumn,
		NumberOfSessions: NumberOfSessionsColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
