//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Courses = newCoursesTable("scheduler", "courses", "")

type coursesTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	Name      postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CoursesTable struct {
	coursesTable

	EXCLUDED coursesTable
}

// AS creates new CoursesTable with assigned alias
func (a CoursesTable) AS(alias string) *CoursesTable {
	return newCoursesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CoursesTable with assigned schema name
func (a CoursesTable) FromSchema(schemaName string) *CoursesTable {
	return newCoursesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CoursesTable with assigned table prefix
func (a CoursesTable) WithPrefix(prefix string) *CoursesTable {
	return newCoursesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CoursesTable with assigned table suffix
func (a CoursesTable) WithSuffix(suffix string) *CoursesTable {
	return newCoursesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCoursesTable(schemaName, tableName, alias string) *CoursesTable {
	return &CoursesTable{
		coursesTable: newCoursesTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newCoursesTableImpl("", "excluded", ""),
	}
}

func newCoursesTableImpl(schemaName, tableName, alias string) coursesTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		NameColumn      = postgres.StringColumn("name")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{NameColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = postgres.ColumnList{CreatedAtColumn}
	)

	return coursesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Name:      NameColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
