//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Rooms = newRoomsTable("scheduler", "rooms", "")

type roomsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	Name      postgres.ColumnString
	Type      postgres.ColumnString
	Building  postgres.ColumnString
	Capacity  postgres.ColumnInteger
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type RoomsTable struct {
	roomsTable

	EXCLUDED roomsTable
}

// AS creates new RoomsTable with assigned alias
func (a RoomsTable) AS(alias string) *RoomsTable {
	return newRoomsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RoomsTable with assigned schema name
func (a RoomsTable) FromSchema(schemaName string) *RoomsTable {
	return newRoomsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RoomsTable with assigned table prefix
func (a RoomsTable) WithPrefix(prefix string) *RoomsTable {
	return newRoomsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RoomsTable with assigned table suffix
func (a RoomsTable) WithSuffix(suffix string) *RoomsTable {
	return newRoomsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRoomsTable(schemaName, tableName, alias string) *RoomsTable {
	return &RoomsTable{
		roomsTable: newRoomsTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newRoomsTableImpl("", "excluded", ""),
	}
}

func newRoomsTableImpl(schemaName, tableName, alias string) roomsTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		NameColumn      = postgres.StringColumn("name")
		TypeColumn      = postgres.StringColumn("type")
		BuildingColumn  = postgres.StringColumn("building")
		CapacityColumn  = postgres.IntegerColumn("capacity")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, NameColumn, TypeColumn, BuildingColumn, CapacityColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{NameColumn, TypeColumn, BuildingColumn, CapacityColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = postgres.ColumnList{CreatedAtColumn}
	)

	return roomsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Name:      NameColumn,
		Type:      TypeColumn,
		Building:  BuildingColumn,
		Capacity:  CapacityColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
