//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var RoomTypes = newRoomTypesTable("scheduler", "room_types", "")

type roomTypesTable struct {
	postgres.Table

	// Columns
	Name      postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type RoomTypesTable struct {
	roomTypesTable

	EXCLUDED roomTypesTable
}

// AS creates new RoomTypesTable with assigned alias
func (a RoomTypesTable) AS(alias string) *RoomTypesTable {
	return newRoomTypesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RoomTypesTable with assigned schema name
func (a RoomTypesTable) FromSchema(schemaName string) *RoomTypesTable {
	return newRoomTypesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RoomTypesTable with assigned table prefix
func (a RoomTypesTable) WithPrefix(prefix string) *RoomTypesTable {
	return newRoomTypesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RoomTypesTable with assigned table suffix
func (a RoomTypesTable) WithSuffix(suffix string) *RoomTypesTable {
	return newRoomTypesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRoomTypesTable(schemaName, tableName, alias string) *RoomTypesTable {
	return &RoomTypesTable{
		roomTypesTable: newRoomTypesTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newRoomTypesTableImpl("", "excluded", ""),
	}
}

func newRoomTypesTableImpl(schemaName, tableName, alias string) roomTypesTable {
	var (
		NameColumn      = postgres.StringColumn("name")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{NameColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = postgres.ColumnList{CreatedAtColumn}
	)

	return roomTypesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Name:      NameColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
