//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Schedules = newSchedulesTable("scheduler", "schedules", "")

// Stores the output of the scheduling algorithm
type schedulesTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	Name      postgres.ColumnString // Schedule identifier (e.g., Fall 2025 Schedule)
	CreatedAt postgres.ColumnTimestamp
	Sessions  postgres.ColumnString // JSONB array: [{course_id, room_id, day (0-6), start_time (mins), end_time (mins)}, ...]

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SchedulesTable struct {
	schedulesTable

	EXCLUDED schedulesTable
}

// AS creates new SchedulesTable with assigned alias
func (a SchedulesTable) AS(alias string) *SchedulesTable {
	return newSchedulesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SchedulesTable with assigned schema name
func (a SchedulesTable) FromSchema(schemaName string) *SchedulesTable {
	return newSchedulesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SchedulesTable with assigned table prefix
func (a SchedulesTable) WithPrefix(prefix string) *SchedulesTable {
	return newSchedulesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SchedulesTable with assigned table suffix
func (a SchedulesTable) WithSuffix(suffix string) *SchedulesTable {
	return newSchedulesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSchedulesTable(schemaName, tableName, alias string) *SchedulesTable {
	return &SchedulesTable{
		schedulesTable: newSchedulesTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newSchedulesTableImpl("", "excluded", ""),
	}
}

func newSchedulesTableImpl(schemaName, tableName, alias string) schedulesTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		NameColumn      = postgres.StringColumn("name")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		SessionsColumn  = postgres.StringColumn("sessions")
		allColumns      = postgres.ColumnList{IDColumn, NameColumn, CreatedAtColumn, SessionsColumn}
		mutableColumns  = postgres.ColumnList{NameColumn, CreatedAtColumn, SessionsColumn}
		defaultColumns  = postgres.ColumnList{CreatedAtColumn}
	)

	return schedulesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Name:      NameColumn,
		CreatedAt: CreatedAtColumn,
		Sessions:  SessionsColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
